### ISSUE TITLE
有bug

### ISSUE THREAD

**Issue by KoolMagic** [davidleitw/socket#3]
https://github.com/davidleitw/socket/blob/master/address/inet_aton_ex.c

这段代码里面，指针是野指针。

应该加上这个

    naddr1 = new in_addr();
    naddr2 = new in_addr();

并在执行逻辑之后删掉

    delete naddr1;
    delete naddr2;

**Comment by davidleitw** [comment]
@Long-Yucheng 的確，當初寫的太趕沒有測試，感謝提醒!

這幾天有時間來修，還是你想提個PR?

**Comment by Long-Yucheng** [comment]
> 

你好，很高兴看到你的回复。就是当时看代码，然后留个言说一下问题。

**Comment by KoolMagic** [comment]
> @Long-Yucheng 的確，當初寫的太趕沒有測試，感謝提醒!
> 
> 這幾天有時間來修，還是你想提個PR?

你好，很高兴看到你的回复。就是当时看代码，然后留个言说一下问题。
